// Copyright (c) 2023 Direct Drive Technology Co., Ltd. All rights reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef TEMPLATE_ROS2_CONTROLLER__TEMPLATE_ROS2_CONTROLLER_HPP_
#define TEMPLATE_ROS2_CONTROLLER__TEMPLATE_ROS2_CONTROLLER_HPP_

#include <chrono>
#include <memory>
#include <string>
#include <vector>

#include "controller_interface/controller_interface.hpp"
#include "geometry_msgs/msg/point_stamped.hpp"
#include "geometry_msgs/msg/pose_with_covariance_stamped.hpp"
#include "geometry_msgs/msg/twist.hpp"
#include "geometry_msgs/msg/twist_with_covariance_stamped.hpp"
#include "geometry_msgs/msg/vector3.hpp"
#include "hardware_interface/types/hardware_interface_type_values.hpp"
#include "nav_msgs/msg/odometry.hpp"
#include "rclcpp/rclcpp.hpp"
#include "rclcpp_lifecycle/node_interfaces/lifecycle_node_interface.hpp"
#include "rclcpp_lifecycle/state.hpp"
#include "semantic_components/imu_sensor.hpp"
#include "sensor_msgs/msg/imu.hpp"
#include "sensor_msgs/msg/joint_state.hpp"
#include "sensor_msgs/msg/joy.hpp"
#include "std_msgs/msg/string.hpp"
#include "tf2/LinearMath/Quaternion.h"
#include "tf2_geometry_msgs/tf2_geometry_msgs.hpp"
#include "tf2_ros/transform_broadcaster.h"
// auto-generated by generate_parameter_library
#include <template_ros2_controller/template_ros2_controller_parameters.hpp>
// Standard message types for motion command
#include "geometry_msgs/msg/twist.hpp"
#include "std_msgs/msg/float64.hpp"
// State machine and robot state
#include "fsm/state_machine.hpp"
#include "robot_state/robot_state.hpp"

namespace robot_locomotion
{
// 对对象先进行引用包装，再进行可选包装
// optional表示接口可能存在也可能不存在（可检查，避免空指针）
// reference_wrapper用于包装引用类型，使其可以存储在std::optional中
using LoanedCommandInterface =
  std::optional<std::reference_wrapper<hardware_interface::LoanedCommandInterface>>;
using LoanedStateInterface =
  std::optional<std::reference_wrapper<hardware_interface::LoanedStateInterface>>;
struct Joint
{
  Joint() {}
  LoanedCommandInterface position_command_handle;
  LoanedCommandInterface velocity_command_handle;
  LoanedCommandInterface effort_command_handle;

  LoanedStateInterface position_handle;
  LoanedStateInterface velocity_handle;
  LoanedStateInterface effort_handle;
  std::string name;
};

class TemplateRos2Controller : public controller_interface::ControllerInterface
{
public:
  ~TemplateRos2Controller();
  TemplateRos2Controller();
  controller_interface::InterfaceConfiguration command_interface_configuration() const override;
  controller_interface::InterfaceConfiguration state_interface_configuration() const override;
  controller_interface::CallbackReturn on_init() override;
  controller_interface::return_type update(
    const rclcpp::Time & time, const rclcpp::Duration & period) override;
  controller_interface::CallbackReturn on_configure(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_activate(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_deactivate(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_cleanup(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_error(
    const rclcpp_lifecycle::State & previous_state) override;
  controller_interface::CallbackReturn on_shutdown(
    const rclcpp_lifecycle::State & previous_state) override;

protected:
  std::vector<std::shared_ptr<Joint>> joints_;
  std::vector<std::string> joint_names_;
  std::vector<std::string> sensor_names_;
  std::vector<std::string> command_interface_types_;
  std::vector<std::string> state_interface_types_;
  std::unique_ptr<semantic_components::IMUSensor> imu_sensor_;

  std::shared_ptr<template_ros2_controller::ParamListener> param_listener_;
  template_ros2_controller::Params params_;
  
  // Time synchronization variables
  rclcpp::Time last_update_time_;
  bool time_sync_enabled_;

  // State machine and robot state
  std::unique_ptr<StateMachine> state_machine_;
  RobotState robot_state_;

  // Motion command subscriber (using geometry_msgs/Twist for velocities and std_msgs/Float64 for height)
  rclcpp::Subscription<geometry_msgs::msg::Twist>::SharedPtr motion_cmd_subscriber_;
  rclcpp::Subscription<std_msgs::msg::Float64>::SharedPtr height_cmd_subscriber_;
  std::mutex motion_cmd_mutex_;  // Mutex for thread-safe access to command data
  double latest_lin_vel_x_;  // Latest received linear velocity in x
  double latest_lin_vel_y_;  // Latest received linear velocity in y
  double latest_ang_vel_z_;  // Latest received angular velocity in z
  double latest_height_;  // Latest received height command
  bool motion_cmd_received_;  // Flag to indicate if command has been received

  // Motion command callbacks
  void motionCommandCallback(const geometry_msgs::msg::Twist::SharedPtr msg);
  void heightCommandCallback(const std_msgs::msg::Float64::SharedPtr msg);

  // 更新机器人状态数据
  void updateRobotState(const rclcpp::Time& time, const rclcpp::Duration& period);

};

}  // namespace robot_locomotion
#endif  // TEMPLATE_ROS2_CONTROLLER__TEMPLATE_ROS2_CONTROLLER_HPP_
